[package]
name = "red-leicester-string"
version = "0.1.0"
edition = "2024"

[dependencies]
aho-corasick = "1.1.5"
base64 = { version = "0.23.1", features = ["std"] }
clap = { version = "4.6.6", features = ["derive"] }
encoding_rs = { version = "0.8.35", default-features = false }
memchr = { version = "2.8.3", default-features = false }
memmap = "0.7.0"
rayon = "1.12.0"
strided = "0.2.9"

[dev-dependencies]
rand = "0.10.2"
rstest = "0.26.1"

[[bin]]
name = "stringcheese"
path = "src/main.rs"
